name: Clang-Format Check

on: [push, pull_request]

jobs:
  clang-format-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 30

    - name: Run Clang-Format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '16'
